### ISSUE TITLE
invalid validation for spec with an array of strings

### ISSUE THREAD

**Issue by robdembitel** [redwirelabs/speck#7]
Hi,

I found a bug while validating this spec:

```
struct App.Specs.Location

name "app_specs_location"

attribute :type,          :string,    values: ["location"]
attribute :data do
  attribute :path,        [:string]
end
```

As defined in the spec above `path` must be an array containing values of type `string`.

Validating this _invalid_ payload (it contains an **integer** instead of a string) with Spec should return an error, but it does not.

```
%{"type" => "location", "data" => %{"path" => ["valid string", 3]}}
```

In this case `Speck.validate` returns `{:ok, ...}`

**Comment by amclain** [comment]
Thanks! We're triaging this issue and aim to have a fix next week.

**Comment by amclain** [comment]
Hi @robdembitel,

We have identified this as a feature request and have opened ticket #8 and assigned @abelino to implement it. Speck is intended to work with third-party APIs that may not be the best behaved, and that a user of Speck may not have the ability to change. Due to this, Speck first makes a best-effort to coerce, and then validates. In other words, the attribute type is the output type rather than the input type. However, there are cases where strict validation (validation before coercion) would be helpful, so we're happy to add this feature.

Are you blocked without this?

**Comment by robdembitel** [comment]
Hi @amclain - all good. I am not blocked by this, yet it would be good to get the strict validation as you described.

Just let me know as soon as you have it - Thanks for adding the feature.

**Comment by amclain** [comment]
Hi @robdembitel,

[Strict validation](https://github.com/redwirelabs/speck?tab=readme-ov-file#strict-validation) has been released in [v1.1.0](https://github.com/redwirelabs/speck/releases/tag/v1.1.0). Let us know if you have any other issues.

**Comment by robdembitel** [comment]
@amclain works like a charm. Thanks!

**Comment by amclain** [comment]
Awesome, glad to hear!
